name: Build Snake vs Alien - v1.2

on:
  push:
    branches: [main]
  # This allows you to run the build manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame pyinstaller

      - name: Build Windows Version
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --noconsole --onefile --name "Snake_vs_Alien_v1.2_Win" --icon="assets/icon.ico" --add-data "assets;assets" --add-data "game_data.json;." main.py

      - name: Build Linux Version
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --noconsole --onefile --name "Snake_vs_Alien_v1.2_Linux" --icon="assets/icon.png" --add-data "assets:assets" --add-data "game_data.json:." main.py

      - name: Upload Artifact
        uses: uses/upload-artifact@v4
        with:
          name: Snake-vs-Alien-${{ matrix.os }}
          path: |
            dist/Snake_vs_Alien_v1.2_Win.exe
            dist/Snake_vs_Alien_v1.2_Linux
